#command state
int32 DAMP=0
int32 BALANCE_STAND=1
int32 STOP_MOVE=2
int32 STAND_UP=3
int32 STAND_DOWN=4
int32 RECOVERY_STAND=5
int32 SIT=6
int32 RISE_SIT=7
int32 HELLO=8
int32 DISABLEAUTORECOVERY=9
int32 ABLEAUTORECOVERY=10
int32 SETNORMALMODE=11
int32 SETAIMODE=12
int32 SETSPORTSMODE=13
int32 SETAVOIDANCE=14
int32 UNSETAVOIDANCE=15
int32 SETSTRIKEPOSE=16
int32 UNSETSTRIKEPOSE=17

int32 task
---
int32 respond